"use client";
import { FileText, Brain, MessageSquare, Share2 } from "lucide-react";
import { motion } from "framer-motion";

const features = [
  {
    icon: <FileText className="w-8 h-8 text-blue-400" />,
    title: "AI Resume Builder",
    desc: "Create ATS-friendly resumes that get you hired. Our AI analyzes job descriptions and tailors your resume instantly."
  },
  {
    icon: <Brain className="w-8 h-8 text-purple-400" />,
    title: "Skill Quizzes",
    desc: "Test your knowledge with adaptive quizzes generated by AI. Identify gaps in your skills before the interview."
  },
  {
    icon: <MessageSquare className="w-8 h-8 text-green-400" />,
    title: "Interview Workspace",
    desc: "Practice with a realistic AI interviewer. Get real-time feedback on your tone, pace, and answer quality."
  },
  {
    icon: <Share2 className="w-8 h-8 text-pink-400" />,
    title: "LinkedIn Optimizer",
    desc: "Turn your profile into a recruiter magnet. We generate headlines, summaries, and post ideas for you."
  }
];

interface FeaturesProps {
  onAuthRequest: () => void;
}

export default function Features({ onAuthRequest }: FeaturesProps) {
  return (
    <section id="features" className="py-24 bg-neutral-950">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-5xl font-bold text-white mb-4">
            Everything You Need to <span className="text-blue-500">Succeed</span>
          </h2>
          <p className="text-gray-400 max-w-2xl mx-auto">
            Stop guessing. Let our advanced AI tools guide every step of your career journey.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          {features.map((feature, index) => (
            <motion.div
              key={index}
              onClick={onAuthRequest}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.1 }}
              viewport={{ once: true }}
              className="p-8 rounded-2xl bg-white/5 border border-white/10 hover:border-blue-500/50 transition-colors group cursor-pointer hover:bg-white/10"
            >
              <div className="mb-4 p-3 rounded-lg bg-white/5 w-fit group-hover:scale-110 transition-transform">
                {feature.icon}
              </div>
              <h3 className="text-xl font-bold text-white mb-2">{feature.title}</h3>
              <p className="text-gray-400 text-sm leading-relaxed">
                {feature.desc}
              </p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}